# Generated by Django 3.0.5 on 2020-07-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=55)),
                ('posts', models.ManyToManyField(related_name='tags', to='posts.Post')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
